Update Travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -75,7 +75,16 @@ script:
       cd $TRAVIS_BUILD_DIR/
       curl -L "https://github.com/Tracktion/pluginval/releases/download/latest_release/pluginval_macOS.zip" -o pluginval.zip
       unzip pluginval
-      pluginval.app/Contents/MacOS/pluginval --strictness-level 8 --validate-in-process --validate "$TRAVIS_BUILD_DIR/Plugin/Builds/MacOSX/build/Release/CHOWTapeModel.vst3" || exit 1
+      pluginval_command="pluginval.app/Contents/MacOS/pluginval --strictness-level 8 --validate-in-process --validate '${TRAVIS_BUILD_DIR}/Plugin/Builds/MacOSX/build/Release/CHOWTapeModel.vst3'"
+      max_retry=5
+      counter=0
+      until $pluginval_command
+      do 
+        sleep 1
+        [[ counter -eq $max_retry ]] && echo "Pluginval Failed!" && exit 1
+        echo "Running pluginval again. Try #$counter"
+        ((counter++))
+      done
       # pluginval.app/Contents/MacOS/pluginval --strictness-level 8 --validate-in-process --validate "$TRAVIS_BUILD_DIR/Plugin/Builds/MacOSX/build/Release/CHOWTapeModel.component" || exit 1
     fi
   # - |
